### ISSUE TITLE
Wisdom of the Elders draws 2 cards instead of 1

### ISSUE THREAD

**Issue by Rusgall** [bubblebooy/Artifact-Javascript#2]
Description ability:
Wisdom of the Elders
Active Ability
Active 4: Draw a card.

Now Wisdom of the Elders draws 2 card.
I think the problem is here
`abilityMap.set("Wisdom of the Elders" , function(card,e){`
 ` card.player.draw();card.player.draw()`
 ` return true`
`});`

**Comment by cmavelis** [comment]
Fixed in #3

**Comment by bubblebooy** [comment]
Fixed
