### ISSUE TITLE
[Gank] issue

### ISSUE THREAD

**Issue by Brawlence** [bubblebooy/Artifact-Javascript#6]
Problem: when using [Gank] on an enemy in the not-yet-active lane, HP could go into negatives without properly disposing said enemy and awarding gold to the killing side.

Expected behaviour: [Gank] makes a check if the enemy's HP lies in the negatives, then disposes the dead one and awards gold to the victor.

This is important if the board has Mercenaries (their damage usually is a function of player's gold) or enemies with board-wide passives like Drow Ranger.

**Comment by Brawlence** [comment]
CardEffects.js, line 631:
`board.lanes[lane].collapse()
in a check which ensures that lane is the current lane
should probably collapse() not only the current lane but also the target lane as well.

**Comment by Brawlence** [comment]
Collapsing all lanes with `v.collapse();` (or using the forced update button) still won't immediatelly award gold if the enemy was killed by [Gank]. Notably, the player receives the gold after using the "Pass" button still.

**Comment by bubblebooy** [comment]
Thanks, Fixed
