### ISSUE TITLE
Can't get Artifact Javascript to run on localHost.

### ISSUE THREAD

**Issue by julienlegault** [bubblebooy/Artifact-Javascript#9]
I'm trying to change some of Artifact's rules in my own branch of Artifact Javascript. I am quite new to Node.js and am having some nvm problems as well (although I believe Node requires nvm?). If you could help lead me through getting this repo to run on localHost I can work from there, I understand what javascript I need to change, just can't test it without a running version of my own.

**Comment by bubblebooy** [comment]
I did not use Node.js at all so I am not sure. I used webpack to build it an run a local server.

https://webpack.js.org/guides/getting-started/

You need npm
then navigate into the Artifact directory and the run the commands:
npm install
npm run build
npm run start

**Comment by julienlegault** [comment]
[npm-debug.log](https://github.com/bubblebooy/Artifact-Javascript/files/3144829/npm-debug.log)
I got npm installed for sure, but webpack won't install via npm. When I try to run the commands that you listed in the artifact directory I get the error log above. It might be a dumb reason but I can't parse the file to find an error. 

![image](https://user-images.githubusercontent.com/23064156/57184781-8a869d00-6e8e-11e9-901c-04b028c8dc9d.png)
This is my webpack install error, which I followed the webpack instructions exactly for installation. I read that error as an attempt at installing webpack has already succeed? But I may be wrong on that. Sorry if this is really simple stuff.

**Comment by julienlegault** [comment]
I was being dumb and trying to install npm and webpack via my linux terminal even though I'm running windows. I'm pretty sure the OS that was providing to the webpack and npm installers was not known to them. I've got it working now!
